<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class LLMDetector
{
    /**
     * Detect if text is generated by AI (LLM).
     * Returns an array with 'score' (0-100), 'result' (string explanation), and 'success' (bool).
     */
    public function detect(string $text): array
    {
        $apiKey = env('OPENAI_API_KEY');
        if (empty($apiKey)) {
            return [
                'success' => false,
                'score' => 0,
                'result' => 'AI detection skipped. Please configure OPENAI_API_KEY in your .env file.',
            ];
        }

        try {
            $response = Http::withToken($apiKey)
                ->post('https://api.openai.com/v1/chat/completions', [
                    'model' => env('OPENAI_MODEL', 'gpt-4o-mini'),
                    'messages' => [
                        [
                            'role' => 'system',
                            'content' => 'You are an AI content detection system. Analyze the provided text and determine the probability (0 to 100) that it was written or significantly edited by an LLM. Respond strictly in JSON format with two keys: "score" (integer) and "reason" (short explanation of why).',
                        ],
                        [
                            'role' => 'user',
                            'content' => $text,
                        ],
                    ],
                    'response_format' => ['type' => 'json_object'],
                ]);

            if ($response->successful()) {
                $data = $response->json();
                $content = json_decode($data['choices'][0]['message']['content'], true);
                
                return [
                    'success' => true,
                    'score' => $content['score'] ?? 0,
                    'result' => $content['reason'] ?? 'Analysis complete.',
                ];
            }

            Log::error("OpenAI detection failed: " . $response->body());
        } catch (\Exception $e) {
            Log::error("Error in LLMDetector: " . $e->getMessage());
        }

        return [
            'success' => false,
            'score' => 0,
            'result' => 'Failed to reach OpenAI detection endpoint.',
        ];
    }
}
